#!/usr/bin/perl

use strict;
use warnings;

my $usage = '

This script is parser for the .kaks file generated by KaKs_calculator.

USAGE: perl kaks_parser.pl *.kaks

';

die $usage unless @ARGV;

open OUT, ">>kaks_parsed.txt";
print OUT "Gene name\tPairwise comp\tSliding windows\tMethod\tKa/Ks>=1\tP-Value(Fisher)\n";

while (my $kaks_file = shift @ARGV) {
	open IN, "<$kaks_file" or die "cannot open $kaks_file";
	while (my $line = <IN>) {
		if ($line =~ /([A-Za-z0-9]{1,}\_[A-Za-z0-9]{1,})\_(\w+_\w+)\((\d{1,}\-\d{1,})\)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)\t(\S+)$/) {
			my $geneid = $1;
			my $pairwise = $2;
			my $window = $3;
			my $method = $4;
			my $ka = $5;
			my $ks = $6;
			my $kaks = $7;
			my $pvalue = $8;
			if ($kaks >= 1) {
				print OUT "$geneid\t$pairwise\t$window\t$method\t$kaks\t$pvalue\n";
			}
#			elsif (($kaks <	1) && ($kaks >= 0.8)) {
#				print OUT "$geneid\t$pairwise\t$window\t$seqid\t$method\t\t\t$kaks\t$pvalue\n";
#			}
		}
	}
	close IN;
}

close OUT;

exit;